#!/bin/bash
#SBATCH --job-name="EAM-HEA"
#SBATCH --account=research-me-mse
#SBATCH --partition=compute
#SBATCH -t 96:00:00
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=16G

source activate ace

pacemaker input.yaml
##############

pace_yaml2yace output_potential.yaml
##############

pace_activeset -d fitting_data_info.pckl.gzip output_potential.yaml

https://github.com/ICAMS/python-ace/tree/master/examples

